### NumPy(Numberical Python)

In [1]:
# lets revise the list  data structure we studies in python
#list with different data types

lst = [1, 3.4, True, "ram", 3-5j, 4.5, 1]

In [2]:
type(lst)

list

In [3]:
# list with duplicate values
lst1 = [1,2,3,1,4,3]
print(lst1)

[1, 2, 3, 1, 4, 3]


In [5]:
# nested list
lst2 = [1,2,[4,5],3]
type(lst2)

list

In [6]:
# indexing and slicing
lst2[0]

1

In [7]:
lst2[-1]

3

In [11]:
type(lst2[-1])

int

In [12]:
# slicing
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [13]:
lst[2:6]

[True, 'ram', (3-5j), 4.5]

In [14]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [15]:
lst[::-1]

[1, 4.5, (3-5j), 'ram', True, 3.4, 1]

In [16]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

### NumPy Array

In [ ]:
# install
!pip install numpy

In [17]:
# import
import numpy as np

In [18]:
array()

NameError: name 'array' is not defined

In [20]:
# creating arrays
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
print(a)

[1 2 3 4 5]


In [23]:
b = np.array([1,4,'a'])
b

array(['1', '4', 'a'], dtype='<U21')

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
# type checking
type(a)

numpy.ndarray

In [26]:
type(b)

numpy.ndarray

In [27]:
# importing array in another ways
from numpy import array
a = array([1,2,3])

In [28]:
print(a)

[1 2 3]


In [31]:
# numpy array of integer data
lst = [5,6,7]
arr = np.array(lst)
arr

array([5, 6, 7])

In [35]:
# array creation using data store in tuples
t = (1,2,3,4,5)
arr = np.array(t)
print(arr)

[1 2 3 4 5]


In [36]:
type(arr)

numpy.ndarray

In [38]:
arr = np.array((11,12,13))
arr

array([11, 12, 13])

In [39]:
type(arr)

numpy.ndarray

In [40]:
arr = np.array({3,4,5})

In [41]:
print(arr)

{3, 4, 5}


In [42]:
type(arr)

numpy.ndarray

In [43]:
# To create the 1-D numpy array, you can start with a python list like this:
lst = [1,2,3]

In [45]:
# then use the np.array() method to convert the list into a numpy array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [46]:
# create the tuple of numbers
arr = np.array((4,5,6))
arr

array([4, 5, 6])

In [48]:
# create set
arr = np.array({7,8,9})
arr

array({8, 9, 7}, dtype=object)

In [49]:
type(arr)

numpy.ndarray

In [50]:
z = np.zeros(7)
z

array([0., 0., 0., 0., 0., 0., 0.])

In [51]:
z[0]

np.float64(0.0)

In [53]:
y = np.ones(shape=8, dtype= np.int16)
y

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [55]:
print(y)

[1 1 1 1 1 1 1 1]


np.arange() function in NumPy works like Python's range() to create sequences of numbers. Its syntax is: np.arange(start,end,step)

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
list(range(5,15))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [58]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [59]:
list(range(5,15,2.2))

TypeError: 'float' object cannot be interpreted as an integer

In [60]:
# comparison of range and arange
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
b = np.arange(5,20)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
c = np.arange(3,40,4)
c

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [63]:
d = np.arange(5,15,2.2)
d

array([ 5. ,  7.2,  9.4, 11.6, 13.8])

np.linspace() function creates an array with evenly spaced numbers within a range. It's syntax is : np.linspace(start,end,num)

start : Starting value of the range.

end : Ending value of the range(inclusive).

num (optional) : Number of values to create

In [64]:
f = np.linspace(5,500,67)
f

array([  5. ,  12.5,  20. ,  27.5,  35. ,  42.5,  50. ,  57.5,  65. ,
        72.5,  80. ,  87.5,  95. , 102.5, 110. , 117.5, 125. , 132.5,
       140. , 147.5, 155. , 162.5, 170. , 177.5, 185. , 192.5, 200. ,
       207.5, 215. , 222.5, 230. , 237.5, 245. , 252.5, 260. , 267.5,
       275. , 282.5, 290. , 297.5, 305. , 312.5, 320. , 327.5, 335. ,
       342.5, 350. , 357.5, 365. , 372.5, 380. , 387.5, 395. , 402.5,
       410. , 417.5, 425. , 432.5, 440. , 447.5, 455. , 462.5, 470. ,
       477.5, 485. , 492.5, 500. ])

In [66]:
12.5 - 5, 20-12.5,27.5-20

(7.5, 7.5, 7.5)

In [67]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [68]:
12-1,23-12,34-23

(11, 11, 11)