### NumPy(Numberical Python)

In [2]:
# lets revise the list  data structure we studies in python
#list with different data types

lst = [1, 3.4, True, "ram", 3-5j, 4.5, 1]

In [3]:
type(lst)

list

In [4]:
# list with duplicate values
lst1 = [1,2,3,1,4,3]
print(lst1)

[1, 2, 3, 1, 4, 3]


In [5]:
# nested list
lst2 = [1,2,[4,5],3]
type(lst2)

list

In [6]:
# indexing and slicing
lst2[0]

1

In [7]:
lst2[-1]

3

In [8]:
type(lst2[-1])

int

In [9]:
# slicing
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [10]:
lst[2:6]

[True, 'ram', (3-5j), 4.5]

In [11]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [12]:
lst[::-1]

[1, 4.5, (3-5j), 'ram', True, 3.4, 1]

In [13]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

### NumPy Array

In [14]:
# install
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [15]:
# import
import numpy as np

In [16]:
array()

NameError: name 'array' is not defined

In [ ]:
# creating arrays
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([1,4,'a'])
b

array(['1', '4', 'a'], dtype='<U21')

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
# type checking
type(a)

numpy.ndarray

In [ ]:
type(b)

numpy.ndarray

In [ ]:
# importing array in another ways
from numpy import array
a = array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
# numpy array of integer data
lst = [5,6,7]
arr = np.array(lst)
arr

array([5, 6, 7])

In [ ]:
# array creation using data store in tuples
t = (1,2,3,4,5)
arr = np.array(t)
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array((11,12,13))
arr

array([11, 12, 13])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array({3,4,5})

In [ ]:
print(arr)

{3, 4, 5}


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# To create the 1-D numpy array, you can start with a python list like this:
lst = [1,2,3]

In [ ]:
# then use the np.array() method to convert the list into a numpy array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
# create the tuple of numbers
arr = np.array((4,5,6))
arr

array([4, 5, 6])

In [ ]:
# create set
arr = np.array({7,8,9})
arr

array({8, 9, 7}, dtype=object)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
z = np.zeros(7)
z

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z[0]

np.float64(0.0)

In [ ]:
y = np.ones(shape=8, dtype= np.int16)
y

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [ ]:
print(y)

[1 1 1 1 1 1 1 1]


np.arange() function in NumPy works like Python's range() to create sequences of numbers. Its syntax is: np.arange(start,end,step)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5,15))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [ ]:
list(range(5,15,2.2))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# comparison of range and arange
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = np.arange(5,20)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
c = np.arange(3,40,4)
c

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [ ]:
d = np.arange(5,15,2.2)
d

array([ 5. ,  7.2,  9.4, 11.6, 13.8])

np.linspace() function creates an array with evenly spaced numbers within a range. It's syntax is : np.linspace(start,end,num)

start : Starting value of the range.

end : Ending value of the range(inclusive).

num (optional) : Number of values to create

In [ ]:
f = np.linspace(5,500,67)
f

array([  5. ,  12.5,  20. ,  27.5,  35. ,  42.5,  50. ,  57.5,  65. ,
        72.5,  80. ,  87.5,  95. , 102.5, 110. , 117.5, 125. , 132.5,
       140. , 147.5, 155. , 162.5, 170. , 177.5, 185. , 192.5, 200. ,
       207.5, 215. , 222.5, 230. , 237.5, 245. , 252.5, 260. , 267.5,
       275. , 282.5, 290. , 297.5, 305. , 312.5, 320. , 327.5, 335. ,
       342.5, 350. , 357.5, 365. , 372.5, 380. , 387.5, 395. , 402.5,
       410. , 417.5, 425. , 432.5, 440. , 447.5, 455. , 462.5, 470. ,
       477.5, 485. , 492.5, 500. ])

In [ ]:
12.5 - 5, 20-12.5,27.5-20

(7.5, 7.5, 7.5)

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
12-1,23-12,34-23

(11, 11, 11)

In [ ]:
# randint
a = np.random.randint(1,20,5)
a

array([19,  7,  7, 18, 16], dtype=int32)

In [ ]:
# you can use random.rand() to create an array of random numbers between 0 and 1
b = np.random.rand(10)
b

array([0.1362153 , 0.34444196, 0.30565782, 0.36644805, 0.14263285,
       0.06296697, 0.4510317 , 0.61685697, 0.81102749, 0.83277747])

In [ ]:
c = np.random.rand()
c

0.33297018412075285

In [ ]:
b

array([0.1362153 , 0.34444196, 0.30565782, 0.36644805, 0.14263285,
       0.06296697, 0.4510317 , 0.61685697, 0.81102749, 0.83277747])

In [ ]:
c

0.33297018412075285

In [ ]:
# in numpy you can create empty array by using np.empty()

l = []
l

[]

In [ ]:
t = ()
t

()

In [ ]:
s = {}
s

{}

In [ ]:
type(s)

dict

In [ ]:
s = set()
s

set()

In [ ]:
type(s)

set

In [ ]:
a = np.empty(5)
a

array([ 5. ,  7.2,  9.4, 11.6, 13.8])

In [ ]:
b = np.empty(18)
b

array([0.00000000e+000, 1.58101007e-322,             nan, 4.94065646e-324,
       2.35570500e-320, 4.94065646e-324, 1.25877562e-311, 1.25877562e-311,
       0.00000000e+000, 0.00000000e+000, 1.25875965e-311, 2.35570500e-320,
       4.94065646e-324, 1.25876173e-311, 2.35570500e-320, 1.25877807e-311,
       1.23516411e-322, 2.12199579e-314])

In [ ]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

### Array Indexing
In NumPy arrays, just like in Python lists, each element has an index number that starts from 0

In NumPy arrays, negative indexing lets you access elements from the end. For example:

-1 gives the last element.

-2 gives the second-to-last element.

If the array is [1, 2, 3, 4, 5]:

array[-1] is 5

array[-2] is 4.

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

np.int64(4)

In [ ]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
print(arr[0])
print(arr[4])
print(arr[5])

1
5


IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
print(arr[0])
print(arr[3])
try:
    print(arr[5])
except Exception as e:
    print(e)

1
4
index 5 is out of bounds for axis 0 with size 5


In [ ]:
# boolean indexing
lst = [1,2,3,4,5,6,7,8,9,10]
print(lst)

# create an array of numbers
numbers = np.array(lst)
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
1%2

1

In [ ]:
10%2

0

In [ ]:
10//2

5

In [ ]:
10%3

1

In [ ]:
10/3

3.3333333333333335

In [ ]:
10 // 3

3

In [ ]:
1 == 0

False

In [ ]:
1 != 0

True

In [ ]:
1 % 2 == 0

False

In [ ]:
10 % 2 == 0

True

In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
numbers % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
numbers % 2 != 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
numbers[5]

np.int64(6)

In [ ]:
numbers[numbers % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
numbers[numbers % 2 != 0]

array([1, 3, 5, 7, 9])

In [ ]:
# select only odd numbers from the array
odd_numbers = numbers[numbers % 2 == 1]
print(odd_numbers)

odd_num = numbers[numbers % 2 != 0]
print(odd_num)

[1 3 5 7 9]
[1 3 5 7 9]


In [ ]:
# select only even numbers from the array
print(numbers[numbers % 2 == 0])

[ 2  4  6  8 10]


In [ ]:
l1 = [1,2]
l2 = [3,4]
print(l1+l2)

[1, 2, 3, 4]


In [ ]:
a1 = np.array([1,2])
a2 = np.array([3,4])
print(a1+a2)

[4 6]


In [ ]:
# create an array of numbers
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers[numbers % 2 == 0])

# change all odd numbers to -100
numbers[numbers % 2 != 0] = -100
print(numbers)

[ 2  4  6  8 10]
[-100    2 -100    4 -100    6 -100    8 -100   10]


In [ ]:
age = np.array([23,25,28,-15,34,-20])
print(age > 0)
print(age[age > 0])

[ True  True  True False  True False]
[23 25 28 34]


In [ ]:
age = np.array([23,25,28,-15,34,-20])
print(age)
age[age < 0] = 0
print(age)

[ 23  25  28 -15  34 -20]
[23 25 28  0 34  0]


### Fancy indexing in NumPy allows you to select elements from an array using a list of specific index.It picks those specific elements and creates a new array.

In [ ]:
# fancy indexing
# creating the numpy array
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers)

# select elements at index 1,2,6,7
elements = numbers[[1,2,6,7]]
print(elements)

[1 2 3 4 5 6 7 8]
[2 3 7 8]


### Array Slicing

In [17]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access the first 4 elements of the array
sliced_number = numbers[:4]
print(sliced_number)

[2 4 6 8]


In [18]:
# create numpy array
numbers = np.array([2,4,6,8,10,12,14])

sliced_number = numbers[1:3]
print(sliced_number)

[4 6]


In [19]:
print(numbers[2:])

[ 6  8 10 12 14]


In [20]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access the elements at even index
sliced_numbers = numbers[0::2]
print(sliced_numbers)

[ 2  6 10 14]


In [21]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access every third elements of the array
sliced_numbers = numbers[::3]
print(sliced_numbers)

[ 2  8 14]


In [23]:
numbers
print(numbers[1:5])

[ 4  6  8 10]


In [24]:
print(numbers[1:8:3])

[ 4 10]


In [25]:
print(numbers[1::2])

[ 4  8 12]


In [26]:
print(numbers[::2])

[ 2  6 10 14]


In [28]:
numbers
print(numbers[::-2])

[14 10  6  2]


In [29]:
numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [30]:
numbers[::-1]

array([14, 12, 10,  8,  6,  4,  2])

### Negative slicing in NumPy allows you to access elements from the end of an array using negative indices.

In [31]:
# Negative slicing

# create the 1-D numpy array
arr = np.array([1,2,3,4,5,6])

# slice the last 3 elements of the array
slice_arr = arr[-3:]
print(slice_arr)

[4 5 6]


In [34]:
arr = np.array([1,2,3,4,5,6])

# slice the array in reverse order
slice_arr = arr[-1::-1]
print(slice_arr)

[6 5 4 3 2 1]


In [35]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# create reverse array
reverse_numbers = numbers[::-1]
print(reverse_numbers)

[14 12 10  8  6  4  2]


### Array Attributes

Attributes and Their Meanings:

ndim: Number of dimensions (e.g., 1 for a 1D array).

shape: Size of the array in each dimension (e.g., length for 1D).

size: Total number of elements in the array.

dtype: Type of data stored in the array.

itemsize: Size of each element in bytes.

nbytes: Total memory used by the array (itemsize × size).

In [37]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# give the array dimension
print('Number of dimension:', numbers.ndim)

# get shape of the array
print('Shape:',numbers.shape)

Number of dimension: 1
Shape: (7,)


In [41]:
number1 = np.array([2,4,6,8,10,'a'])
print(number1)
print('Data type of first array:',number1.dtype)

# create an array of int type
int_numbers = np.array([2,4,6,8,10,12,13])

# create an array of float type
float_numbers = np.array([3.4,5.6,7.8,9.1])


# check data type of numbers
print('Data type of second array:',int_numbers.dtype)

# check data type of float array
print('Data type of third array:',float_numbers.dtype)

['2' '4' '6' '8' '10' 'a']
Data type of first array: <U21
Data type of second array: int64
Data type of third array: float64


In [43]:
# we use size attribute to find the total number of elements in the array
first = np.array([1,3,4,6,8])
second = np.array([2,4,6,8,1,10,13,12])

print('size of the first array:',first.size)
print('size of the second array:',second.size)

size of the first array: 5
size of the second array: 8
