### NumPy(Numberical Python)

In [33]:
# lets revise the list  data structure we studies in python
#list with different data types

lst = [1, 3.4, True, "ram", 3-5j, 4.5, 1]

In [34]:
type(lst)

list

In [35]:
# list with duplicate values
lst1 = [1,2,3,1,4,3]
print(lst1)

[1, 2, 3, 1, 4, 3]


In [36]:
# nested list
lst2 = [1,2,[4,5],3]
type(lst2)

list

In [37]:
# indexing and slicing
lst2[0]

1

In [38]:
lst2[-1]

3

In [39]:
type(lst2[-1])

int

In [40]:
# slicing
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [41]:
lst[2:6]

[True, 'ram', (3-5j), 4.5]

In [42]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

In [43]:
lst[::-1]

[1, 4.5, (3-5j), 'ram', True, 3.4, 1]

In [44]:
lst

[1, 3.4, True, 'ram', (3-5j), 4.5, 1]

### NumPy Array

In [45]:
# install
!pip install numpy

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [46]:
# import
import numpy as np

In [47]:
array()

NameError: name 'array' is not defined

In [ ]:
# creating arrays
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([1,4,'a'])
b

array(['1', '4', 'a'], dtype='<U21')

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
# type checking
type(a)

numpy.ndarray

In [ ]:
type(b)

numpy.ndarray

In [ ]:
# importing array in another ways
from numpy import array
a = array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
# numpy array of integer data
lst = [5,6,7]
arr = np.array(lst)
arr

array([5, 6, 7])

In [ ]:
# array creation using data store in tuples
t = (1,2,3,4,5)
arr = np.array(t)
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array((11,12,13))
arr

array([11, 12, 13])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array({3,4,5})

In [ ]:
print(arr)

{3, 4, 5}


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# To create the 1-D numpy array, you can start with a python list like this:
lst = [1,2,3]

In [ ]:
# then use the np.array() method to convert the list into a numpy array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
# create the tuple of numbers
arr = np.array((4,5,6))
arr

array([4, 5, 6])

In [ ]:
# create set
arr = np.array({7,8,9})
arr

array({8, 9, 7}, dtype=object)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
z = np.zeros(7)
z

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z[0]

np.float64(0.0)

In [ ]:
y = np.ones(shape=8, dtype= np.int16)
y

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [ ]:
print(y)

[1 1 1 1 1 1 1 1]


np.arange() function in NumPy works like Python's range() to create sequences of numbers. Its syntax is: np.arange(start,end,step)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5,15))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [ ]:
list(range(5,15,2.2))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# comparison of range and arange
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = np.arange(5,20)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
c = np.arange(3,40,4)
c

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [ ]:
d = np.arange(5,15,2.2)
d

array([ 5. ,  7.2,  9.4, 11.6, 13.8])

np.linspace() function creates an array with evenly spaced numbers within a range. It's syntax is : np.linspace(start,end,num)

start : Starting value of the range.

end : Ending value of the range(inclusive).

num (optional) : Number of values to create

In [ ]:
f = np.linspace(5,500,67)
f

array([  5. ,  12.5,  20. ,  27.5,  35. ,  42.5,  50. ,  57.5,  65. ,
        72.5,  80. ,  87.5,  95. , 102.5, 110. , 117.5, 125. , 132.5,
       140. , 147.5, 155. , 162.5, 170. , 177.5, 185. , 192.5, 200. ,
       207.5, 215. , 222.5, 230. , 237.5, 245. , 252.5, 260. , 267.5,
       275. , 282.5, 290. , 297.5, 305. , 312.5, 320. , 327.5, 335. ,
       342.5, 350. , 357.5, 365. , 372.5, 380. , 387.5, 395. , 402.5,
       410. , 417.5, 425. , 432.5, 440. , 447.5, 455. , 462.5, 470. ,
       477.5, 485. , 492.5, 500. ])

In [ ]:
12.5 - 5, 20-12.5,27.5-20

(7.5, 7.5, 7.5)

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
12-1,23-12,34-23

(11, 11, 11)

In [ ]:
# randint
a = np.random.randint(1,20,5)
a

array([19,  7,  7, 18, 16], dtype=int32)

In [ ]:
# you can use random.rand() to create an array of random numbers between 0 and 1
b = np.random.rand(10)
b

array([0.1362153 , 0.34444196, 0.30565782, 0.36644805, 0.14263285,
       0.06296697, 0.4510317 , 0.61685697, 0.81102749, 0.83277747])

In [ ]:
c = np.random.rand()
c

0.33297018412075285

In [ ]:
b

array([0.1362153 , 0.34444196, 0.30565782, 0.36644805, 0.14263285,
       0.06296697, 0.4510317 , 0.61685697, 0.81102749, 0.83277747])

In [ ]:
c

0.33297018412075285

In [ ]:
# in numpy you can create empty array by using np.empty()

l = []
l

[]

In [ ]:
t = ()
t

()

In [ ]:
s = {}
s

{}

In [ ]:
type(s)

dict

In [ ]:
s = set()
s

set()

In [ ]:
type(s)

set

In [ ]:
a = np.empty(5)
a

array([ 5. ,  7.2,  9.4, 11.6, 13.8])

In [ ]:
b = np.empty(18)
b

array([0.00000000e+000, 1.58101007e-322,             nan, 4.94065646e-324,
       2.35570500e-320, 4.94065646e-324, 1.25877562e-311, 1.25877562e-311,
       0.00000000e+000, 0.00000000e+000, 1.25875965e-311, 2.35570500e-320,
       4.94065646e-324, 1.25876173e-311, 2.35570500e-320, 1.25877807e-311,
       1.23516411e-322, 2.12199579e-314])

In [ ]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

### Array Indexing
In NumPy arrays, just like in Python lists, each element has an index number that starts from 0

In NumPy arrays, negative indexing lets you access elements from the end. For example:

-1 gives the last element.

-2 gives the second-to-last element.

If the array is [1, 2, 3, 4, 5]:

array[-1] is 5

array[-2] is 4.

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

np.int64(4)

In [ ]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
print(arr[0])
print(arr[4])
print(arr[5])

1
5


IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
print(arr[0])
print(arr[3])
try:
    print(arr[5])
except Exception as e:
    print(e)

1
4
index 5 is out of bounds for axis 0 with size 5


In [ ]:
# boolean indexing
lst = [1,2,3,4,5,6,7,8,9,10]
print(lst)

# create an array of numbers
numbers = np.array(lst)
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
1%2

1

In [ ]:
10%2

0

In [ ]:
10//2

5

In [ ]:
10%3

1

In [ ]:
10/3

3.3333333333333335

In [ ]:
10 // 3

3

In [ ]:
1 == 0

False

In [ ]:
1 != 0

True

In [ ]:
1 % 2 == 0

False

In [ ]:
10 % 2 == 0

True

In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
numbers % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
numbers % 2 != 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
numbers[5]

np.int64(6)

In [ ]:
numbers[numbers % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
numbers[numbers % 2 != 0]

array([1, 3, 5, 7, 9])

In [ ]:
# select only odd numbers from the array
odd_numbers = numbers[numbers % 2 == 1]
print(odd_numbers)

odd_num = numbers[numbers % 2 != 0]
print(odd_num)

[1 3 5 7 9]
[1 3 5 7 9]


In [ ]:
# select only even numbers from the array
print(numbers[numbers % 2 == 0])

[ 2  4  6  8 10]


In [ ]:
l1 = [1,2]
l2 = [3,4]
print(l1+l2)

[1, 2, 3, 4]


In [ ]:
a1 = np.array([1,2])
a2 = np.array([3,4])
print(a1+a2)

[4 6]


In [ ]:
# create an array of numbers
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers[numbers % 2 == 0])

# change all odd numbers to -100
numbers[numbers % 2 != 0] = -100
print(numbers)

[ 2  4  6  8 10]
[-100    2 -100    4 -100    6 -100    8 -100   10]


In [ ]:
age = np.array([23,25,28,-15,34,-20])
print(age > 0)
print(age[age > 0])

[ True  True  True False  True False]
[23 25 28 34]


In [ ]:
age = np.array([23,25,28,-15,34,-20])
print(age)
age[age < 0] = 0
print(age)

[ 23  25  28 -15  34 -20]
[23 25 28  0 34  0]


### Fancy indexing in NumPy allows you to select elements from an array using a list of specific index.It picks those specific elements and creates a new array.

In [ ]:
# fancy indexing
# creating the numpy array
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers)

# select elements at index 1,2,6,7
elements = numbers[[1,2,6,7]]
print(elements)

[1 2 3 4 5 6 7 8]
[2 3 7 8]


### Array Slicing

In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access the first 4 elements of the array
sliced_number = numbers[:4]
print(sliced_number)

[2 4 6 8]


In [ ]:
# create numpy array
numbers = np.array([2,4,6,8,10,12,14])

sliced_number = numbers[1:3]
print(sliced_number)

[4 6]


In [ ]:
print(numbers[2:])

[ 6  8 10 12 14]


In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access the elements at even index
sliced_numbers = numbers[0::2]
print(sliced_numbers)

[ 2  6 10 14]


In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access every third elements of the array
sliced_numbers = numbers[::3]
print(sliced_numbers)

[ 2  8 14]


In [ ]:
numbers
print(numbers[1:5])

[ 4  6  8 10]


In [ ]:
print(numbers[1:8:3])

[ 4 10]


In [ ]:
print(numbers[1::2])

[ 4  8 12]


In [ ]:
print(numbers[::2])

[ 2  6 10 14]


In [ ]:
numbers
print(numbers[::-2])

[14 10  6  2]


In [ ]:
numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
numbers[::-1]

array([14, 12, 10,  8,  6,  4,  2])

### Negative slicing in NumPy allows you to access elements from the end of an array using negative indices.

In [ ]:
# Negative slicing

# create the 1-D numpy array
arr = np.array([1,2,3,4,5,6])

# slice the last 3 elements of the array
slice_arr = arr[-3:]
print(slice_arr)

[4 5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6])

# slice the array in reverse order
slice_arr = arr[-1::-1]
print(slice_arr)

[6 5 4 3 2 1]


In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# create reverse array
reverse_numbers = numbers[::-1]
print(reverse_numbers)

[14 12 10  8  6  4  2]


### Array Attributes

Attributes and Their Meanings:

ndim: Number of dimensions (e.g., 1 for a 1D array).

shape: Size of the array in each dimension (e.g., length for 1D).

size: Total number of elements in the array.

dtype: Type of data stored in the array.

itemsize: Size of each element in bytes.

nbytes: Total memory used by the array (itemsize × size).

In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# give the array dimension
print('Number of dimension:', numbers.ndim)

# get shape of the array
print('Shape:',numbers.shape)

Number of dimension: 1
Shape: (7,)


In [ ]:
number1 = np.array([2,4,6,8,10,'a'])
print(number1)
print('Data type of first array:',number1.dtype)

# create an array of int type
int_numbers = np.array([2,4,6,8,10,12,13])

# create an array of float type
float_numbers = np.array([3.4,5.6,7.8,9.1])


# check data type of numbers
print('Data type of second array:',int_numbers.dtype)

# check data type of float array
print('Data type of third array:',float_numbers.dtype)

['2' '4' '6' '8' '10' 'a']
Data type of first array: <U21
Data type of second array: int64
Data type of third array: float64


In [ ]:
# we use size attribute to find the total number of elements in the array
first = np.array([1,3,4,6,8])
second = np.array([2,4,6,8,1,10,13,12])

print('size of the first array:',first.size)
print('size of the second array:',second.size)

size of the first array: 5
size of the second array: 8


In [57]:
# We use itemsize attribute to find the size(in bytes) of each element in the array.
# create a default 1-D array of integers
array1 = np.array([6,7,8,9,10,11])

# create a 1-D array of 16-bit integers
array2 = np.array([6,7,8,9,10,11], dtype=np.int16)

# create a 1-D array of floats
array3 = np.array([1.2,2.4,5.6,7.8], dtype= np.float64)

print(array1)
print(array2)
print(array3)

print(array1.itemsize)
print(array2.itemsize)
print(array3.itemsize)

[ 6  7  8  9 10 11]
[ 6  7  8  9 10 11]
[1.2 2.4 5.6 7.8]
8
2
8


In [59]:
# nbytes finds the total number of bytes consumed by elements in the array.
print(array1.nbytes)
print(array2.nbytes)
print(array3.nbytes)

48
12
32


In [62]:
array4 = np.array([1,2,3,4,5],dtype= np.float32)
print(array4)
print(array4.itemsize)
print(array4.nbytes)

[1. 2. 3. 4. 5.]
4
20


### 1D Array Operations in Numpy

In [ ]:
# 1.Mathematical Operations
import numpy as np

In [64]:
first = np.array([1,5,5,7])
second = np.array([2,3,6,8])

# using the + operator
sum = first + second
print(sum)

[ 3  8 11 15]


In [65]:
first = np.array([1,5,5,7])
second = np.array([2,3,6,8])

# using the add() function
sum = np.add(first,second)
print(sum)

[ 3  8 11 15]


In [66]:
12/3

4.0

In [67]:
13/0

ZeroDivisionError: division by zero

In [73]:
first = np.array([3,9,27,81])
second = np.array([3,3,3,3])

result = first / second
print(result)
print(type(result[1]))

[ 1.  3.  9. 27.]
<class 'numpy.float64'>


In [74]:
np.divide(first,second)

array([ 1.,  3.,  9., 27.])

In [75]:
np.multiply(first,second)

array([  9,  27,  81, 243])

In [76]:
first = np.array([3,9,27,81])
second = np.array([1,4,6,8])

# usinfg the divide() function
result = np.divide(first,second)
print(result)

[ 3.     2.25   4.5   10.125]


In [77]:
2/0

ZeroDivisionError: division by zero

In [79]:
import warnings as w
w.filterwarnings('ignore')

array1 = np.array([2,8,16,32])
array2 = np.array([0,4,0,8])
result = np.divide(array1,array2)
print(result)

[inf  2. inf  4.]


In [80]:
first = np.array([1,3,5,7])
second = np.array([1,2,3,4])

# using the ** operator
result = first ** second
print(result)

[   1    9  125 2401]


In [83]:
first = np.array([1,3,5,7])
second = np.array([1,2,3,4])

# using the power() function
result = np.power(second,first)
print(result)

[    1     8   243 16384]


In [84]:
# 2. Comparison Operators

1 > 3

False

In [85]:
[1,4,5,7] > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [86]:
first_array = np.array([1,2,3,4])
second_array = np.array([4,2,3,1])

print(first_array)
print(second_array)

[1 2 3 4]
[4 2 3 1]


In [87]:
4 < 3

False

In [88]:
2 < 3

True

In [90]:
print(first_array)
print(second_array)

[1 2 3 4]
[4 2 3 1]


In [92]:
# less than operator
result = first_array < second_array
print(result)

# less than or equal to operator
result = first_array <= second_array
print(result)

[ True False False False]
[ True  True  True False]


In [93]:
first_array

array([1, 2, 3, 4])

In [94]:
second_array

array([4, 2, 3, 1])

In [97]:
#  greater than operator
result = first_array > second_array
print(result)

# equal to operator
result = first_array == second_array
print(result)

# not equal to
result = first_array != second_array
print(result)

[False False False  True]
[False  True  True False]
[ True False False  True]


In [ ]:
a = np.array([10,12,15,21])
b = np.array([15,12,10,21])

# use of less()
result = np.less(a,b)  # <
print(result)

# use of less_equal()
result = np.less_equal(a,b)  # <=
print(result)

# use of greater()
result = np.greater(a,b) # >
print(result)

# use of greater_equal()
result = np.greater_equal(a,b)    # >=
print(result)

# use of equal()
result = np.equal(a,b)  # ==
print(result)

# use of not_equal()
result = np.not_equal(a,b)
print(result)


[ True False False False]
[ True  True False  True]
[False False  True False]
[False  True  True  True]
[False  True False  True]
[ True False  True False]


In [ ]:
# 3. Logical Operators


# x1 = np.array([True, False, True, False]) x2 = np.array([False, False, True, False])

# Logical AND
# print(np.logical_and(x1, x2))

# Logical OR
# print(np.logical_or(x1, x2))

# Logical NOT
# print(np.logical_not(x1)) print(np.logical_not(x2))

In [105]:
x1 = np.array([True,False,True,False])
x2 = np.array([False,False,True,True])
print(x1)
print(x2)

[ True False  True False]
[False False  True  True]


In [108]:
l = np.logical_and(x1,x2)
print(l)

print(np.logical_or(x1,x2))

print(np.logical_not(x1,x2))

[False False  True False]
[ True False  True  True]
[False  True False  True]


In [109]:
# 4. Statistical Functions

# create a numpy array
marks = np.array([87,77,93,81,85,83])

# compute the mean of marks
mean_marks = np.mean(marks)
print(mean_marks)

84.33333333333333


In [110]:
(87+77+93+81+85+83)/6

84.33333333333333

In [ ]:
# Median
# - Arrange the data in ascending Order
# - Check whether the count of elements is even or odd
# - If count is even, add the middle elements and divide by 2
# - If the count is odd, directly take the middle element as median

In [111]:
marks

array([87, 77, 93, 81, 85, 83])

In [112]:
print(np.median(marks))

84.0


In [114]:
# create a 1D array with 6 elements
array1 = np.array([5,4,2,1,3,6])  # 1,2,3,4,5,6 (6) 3.5
# 1,2,3,4,5,6 --> (3+4)/2 --> 3.5

# calculate the median
median = np.median(array1)
print(median)


array2 = np.array([5,4,3,1,2])
# 1,2,3,4,5 --> 3.0
print(np.median(array2))

3.5
3.0


In [115]:
array2 = np.array([14,15,12,9,5,44,56,4])

# 4,5,9,12,14,15,44,56
print(np.mean(array2))
print(np.median(array2))

19.875
13.0


In [116]:
# create a 1D array with 8 elements
arr1 = np.array([1,2,3,4,5,6,7,8])

# calculate the median
median = np.median(arr1)
print(median)

4.5


 ### Standard deviation is a measure that tells us how spread out or scattered the numbers in a set of data are. It gives us an idea of how much the data values differ from the average or typical value.

In [118]:
# create a numpy array
marks = np.array([86, 83, 81, 82, 85, 84])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

1.707825127659933


In [119]:
# create a numpy array
marks = np.array([16, 23, 1, 72, 45, 99])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

33.84605672091737


In [120]:
# create an  array
array1 = np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [122]:
result1 = np.percentile(array1,0)
print("0th percentile:", result1)
print("Minimun value:",min(array1))

0th percentile: 1.0
Minimun value: 1


In [123]:
print(np.percentile(array1,25))

25.75


In [126]:
# compute the 50th percentile of the array

result1 = np.percentile(array1,50)
print("50th percentile:", result1)
print("median value:",np.median(array1))

50th percentile: 50.5
median value: 50.5


In [127]:
print(np.percentile(array1,75))

75.25


In [129]:
print(max(array1))
print(np.percentile(array1,100))

100
100.0


In [133]:
# create an array
array1 = np.array([2,6,9,16,27,26,91,84])

# find the minimum value of the array
min_val = np.min(array1)

# find the maximum value of the array
max_val = np.max(array1)

# print the results
print("Minimun value:",min_val)
print("Maximun value:",max_val)

Minimun value: 2
Maximun value: 91


### NumPy in N Dimensions

In [135]:
array = np.array([10,20,30])
print(array.ndim)

1


In [140]:
# create 2-D array
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.ndim)

# create 3D array
array2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array2)
print(array2.ndim)

2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [142]:
# create a 2D array with 3 rows and 4 columns
list1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(list1)

np_array = np.array(list1)
print(np_array)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
# 2d array of inhomogeneous shape
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [5,7]])
print(array1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [144]:
# 2d array of homogeneous shape
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [5,7,8]])
print(array1)

[[1 2 3]
 [4 5 6]
 [5 7 8]]


In [145]:
# Indexing in 2D Array
print(array1[1,2])

6


In [146]:
array1[2,1]

np.int64(7)

In [147]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [5, 7, 8]])

In [148]:
array1[1:3,0:2]

array([[4, 5],
       [5, 7]])

In [149]:
# 2d array of different data types
array1 = np.array([[1,2,3],
                   ['a','b','c'],
                   [1.0,2.0,3.0]])
print(array1)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['1.0' '2.0' '3.0']]


 ### It is not recommended to use NumPy arrays with mixed data types. As an alternative we can used Pandas DataFrames for mixed data types

In [1]:
import numpy as np

In [2]:
# create a 3D array with 2 "slices" of 3 rows and 4 columns each
np_array = np.array([[[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12]],
                      [[13,14,15,16],
                       [17,18,19,20],
                       [21,22,23,24]]])
print(np_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [8]:
# create an empty 2-D array with 2 rows and 3 columns
np_array = np.empty((2,3))

print(np_array)

[[6.23042070e-307 7.84576246e-321 0.00000000e+000]
 [6.76847904e-312 0.00000000e+000 1.22387635e-307]]


In [6]:
# create an empty 3-D array with 3 "slices" of 3 rows and 3 columns each
np_array = np.empty((3,3,3))
print(np_array)

[[[6.23042070e-307 7.56587584e-307 7.56592338e-307]
  [6.23053614e-307 6.23053954e-307 9.34609790e-307]
  [8.45593934e-307 9.34600963e-307 9.34598925e-307]]

 [[1.42418715e-306 1.95819401e-306 1.37961370e-306]
  [6.23054633e-307 9.34598926e-307 6.89804132e-307]
  [9.34598926e-307 8.01091099e-307 1.24610927e-306]]

 [[8.90094053e-307 1.02361342e-306 7.56593017e-307]
  [1.60219035e-306 8.90111708e-307 6.89806849e-307]
  [9.34601642e-307 1.42410974e-306 2.56761491e-312]]]


In [12]:
print(np.empty(5))

[6.76865204e-312 6.76865204e-312 6.76865204e-312 6.95187041e-310
 0.00000000e+000]


In [14]:
# create a 2x3 array filled with 0s
numpy_array = np.zeros((2,3))
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# create a 2x3x4 array filled with 1s
numpy_array = np.ones((2,3,4))
print(numpy_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [17]:
# create 3x3 array all filled with the value 9
numpy_array = np.full(shape=(3,3), fill_value= 9)
print(numpy_array)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [18]:
print(np.full((2,5),7))

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [19]:
print(np.full((3,3),9))

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [20]:
print(np.full((4,4),101))

[[101 101 101 101]
 [101 101 101 101]
 [101 101 101 101]
 [101 101 101 101]]


In [28]:
print(np.full(5,7))

[7 7 7 7 7]


In [31]:
print(np.full((2,3,4,2),3))

[[[[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]]


 [[[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]]]


In [33]:
# create 2-D array
arr = np.array([[2,4,6],[1,3,5]])
print(arr)
# print dimension size
print("Array Dimension:", arr.ndim)

[[2 4 6]
 [1 3 5]]
Array Dimension: 2


In [37]:
# create an array with 5 rows and 3 columns
arr = np.zeros((5,3))

print(arr)
print("Dimension of array is :",arr.ndim)
print("\nshape of the array:",arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Dimension of array is : 2

shape of the array: (5, 3)


In [38]:
# create a 3D array
np_array = np.array([[[1,2],[3,4]],
                     [[5,6],[7,8]],
                     [[9,10],[11,12]]])
print(np_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [41]:
print(np_array[2,1,0])

11


In [42]:
print(np_array[1,0,1])

6


In [45]:
print(np_array[1,1,0])

7


In [46]:
print(np_array[1,1,1])

8


In [47]:
print(np_array[2,0,1])

10


In [48]:
print(np_array[1,1,0])

7


In [49]:
print(np_array[2,1,1])

12


In [50]:
print(np_array[2,0,0])

9


In [51]:
print(np_array[0,1,0])

3


In [52]:
print(np_array[1,0,1])

6


In [58]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [60]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [61]:
np.arange(1,50).reshape(7,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [72]:
# create a 3-D array
array1 = np.arange(1,13).reshape(3,2,2)
print(array1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [74]:
# slicing the 3-D array
entire_array = array1[:,:,:]  # slice the entire array
print(entire_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [75]:
second_matrix = array1[1,:,:]  # slice the second matrix
print(second_matrix)

[[5 6]
 [7 8]]


In [76]:
print(entire_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [77]:
second_row_each_matrix = array1[:, 1, :]    # slice the second row of each matrix
print(second_row_each_matrix)

[[ 3  4]
 [ 7  8]
 [11 12]]


In [78]:
print(array1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [79]:
second_column_each_matrix = array1[:, :, 1]    # slice the second column of each matrix
print(second_column_each_matrix)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [85]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np_array)


np_array[1,1] = 55
print(np_array)

np_array[2,1] = 18
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 55  6]
 [ 7 18  9]]


In [87]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np_array)

np_array[2, 2] = 15

print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 15]]


In [89]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
print(array1)

# reshape a 1D array into a 2D array
# with 2 rows and 4 columns
result = np.reshape(array1,(2,4))
print(result)

[1 3 5 7 2 4 6 8]
[[1 3 5 7]
 [2 4 6 8]]


In [92]:
# create a 1D array
array1 = np.array([1, 2, 3, 4, 6, 7, 8, 9])

# reshape the 1D array to a 3D array
result = np.reshape(array1,(2,2,2))
print(result)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [94]:
# create a 1D array
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array1)

# reshape the array into a 2x4 array with 'C' order
result1 = np.reshape(array1,(2,4), order= 'C')
print(result1)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [96]:
# create a 1D array
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array1)

# reshape the array into a 2x4 array with 'F' order
result2 = np.reshape(array1,(2,4), order='F')
print(result2)

[1 2 3 4 5 6 7 8]
[[1 3 5 7]
 [2 4 6 8]]


### Matrix

In [101]:
# create a 2x2 matrix
matrix1 = np.array([[1,2],[3,5]])
print("2x2 matrix:")
print(matrix1)

# create a 3x3  matrix
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3x3 matrix:")
print(matrix2)

2x2 matrix:
[[1 2]
 [3 5]]
3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
# create a 3x3 matrix filled with ones
one_matrix = np.ones((3,3))
print("Matrix filled with ones: ",one_matrix)

# create a 3x3 matrix filled with zeros
zero_matrix = np.zeros((3,3))
print("\nMatrix filled with zeros:",zero_matrix)

Matrix filled with ones:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [109]:
# create a 2D matrix
matrix1 = np.matrix([[1,2],[3,4]])
print(matrix1)
print(type(matrix1))

# create a 2D array
matrix2 = np.array([[1,2],[3,4]])
print(matrix2)
print(type(matrix2))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### Matrix Multiplication

In [110]:
# create NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 0], [1, 2]])
print(array1)
print()
print(array2)
print("Array multiplication: \n", array1 * array2)
print("Array power: \n", array1 ** 2)

[[1 2]
 [3 4]]

[[2 0]
 [1 2]]
Array multiplication: 
 [[2 0]
 [3 8]]
Array power: 
 [[ 1  4]
 [ 9 16]]


In [111]:
# create NumPy matrices
matrix1 = np.matrix([[1, 2], [3, 4]])
matrix2 = np.matrix([[2, 0], [1, 2]])
print(matrix1)
print()
print(matrix2)
print("Matrix multiplication: \n", matrix1 * matrix2)

print("Matrix power: \n", matrix1**2)

[[1 2]
 [3 4]]

[[2 0]
 [1 2]]
Matrix multiplication: 
 [[ 4  4]
 [10  8]]
Matrix power: 
 [[ 7 10]
 [15 22]]


In [112]:
# create two matrices
matrix1 = np.array([[1, 2],
             	      [3, 4]])

matrix2 = np.array([[2, 0],
                    [1, 2]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

matrix1 x matrix2: 
 [[ 4  4]
 [10  8]]


In [113]:
matrix1 @ matrix2

array([[ 4,  4],
       [10,  8]])

In [114]:
# create two matrices of incompatible dimensions
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10]])

# attempt to calculate the dot product
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n", result)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [115]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10]])

# attempt to calculate the dot product
result = np.dot(matrix2, matrix1)

print("matrix1 x matrix2: \n", result)

matrix1 x matrix2: 
 [[39 54 69]
 [49 68 87]]


In [116]:
# create a matrix
matrix1 = np.array([[1, 2],
             	      [3, 4]])

# get transpose of matrix1
result = np.transpose(matrix1)

print(result)

[[1 3]
 [2 4]]


In [123]:
# create a 2x2 identity matrix using eye()
matrix1 = np.eye(2,2)
print("\n2x2 Identity Matrix:")
print(matrix1)

# create a 5x5 identity matrix using identity()
matrix2 = np.identity(5)
print("5x5 Identity Matrix:")
print(matrix2)



2x2 Identity Matrix:
[[1. 0.]
 [0. 1.]]
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# More NumPy array operations :

# Filter
# NumPy where()
# NumPy any()
# NumPy all()
# NumPy stack()
# NumPy sum() / mean()
# NumPy Masked Array
# NumPy flatten()

In [124]:
[[1,2,-1,-2,10,12,20],[1,2,3,-6,1,-10,-1]] < 0

TypeError: '<' not supported between instances of 'list' and 'int'

In [125]:
array1 = np.array([[1,2,-1,-2,10,12,20],
                   [1,2,3,-6,1,-10,-1]])

print("Original array :\n", array1)

print("Identify Negative values:")
print(array1 < 0)

Original array :
 [[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
Identify Negative values:
[[False False  True  True False False False]
 [False False False  True False  True  True]]


In [126]:
array1 = np.array([[1,2,-1,-2,10,12,20],
                   [1,2,3,-6,1,-10,-1]])

print("Original array :\n", array1)

print("Identify non-negative values:")
print(array1 >= 0)

Original array :
 [[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
Identify non-negative values:
[[ True  True False False  True  True  True]
 [ True  True  True False  True False False]]


In [127]:
array1 = np.array([[1,2,-11,2,10,-12,20],
                   [1,2,-13,6,1,10,-10]])
filtered_arr = array1[array1 > 0]
print("The positive values are:",filtered_arr)

The positive values are: [ 1  2  2 10 20  1  2  6  1 10]


### Use of Where

In [129]:
array1 = np.array([[1,2,-1,-2,10,12,20],[1,2,3,-6,1,-10,-1]])
print(array1)

# replace negative values with 0
print(np.where(array1 < 0, 0,array1))

[[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
[[ 1  2  0  0 10 12 20]
 [ 1  2  3  0  1  0  0]]


In [132]:
array1 = np.array([[1,2,-1,-2,10,12,20],[1,2,3,-6,1,-10,-1]])
print(array1)

# replace non-negative values with 0 and negative values with 1
print(np.where(array1 < 0,0, 1))

[[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
[[1 1 0 0 1 1 1]
 [1 1 1 0 1 0 0]]


In [134]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7])

# if element is less than 2 or greater than 6, test condition is True
test_condition1 = (array1 < 2) | (array1 > 6)

# select element of x if test condition is True
# return 0 if test condition is False
result = np.where(test_condition1, array1, 0)
print(result)

[1 0 0 0 0 0 7]


In [135]:
array1

array([1, 2, 3, 4, 5, 6, 7])

In [137]:
# if element is  greater than 2 and less than 6, test condition is True
test_condition2 = (array1 > 2) & (array1 < 6)

# select element of x if test condition is True
# return 0 if test condition is False
result2 = np.where(test_condition2, array1, 0)
print(result2)

[0 0 3 4 5 0 0]


In [138]:
array1 = np.array([1, 2, 3, 4, 5])

# check if any element is smaller than 3
result = np.any(array1 < 3)
print(result)

True


In [139]:
# check if any element is negative
result = np.any(array1 < 0)
print(result)

False


In [141]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# check if any element in each row is greater than 5
result_row = np.any(array1 > 5, axis=1)
print(result_row)

# check if any element in each column is less than 3
result_column = np.any(array1 < 3, axis=0)
print(result_column)

[False  True  True]
[ True  True False]


In [142]:
array1 = np.array([1, 2, 3, 4, 5])

# check if all element is greater than 2
result = np.all(array1 > 2)
print(result)

# check if all element is less than 8
result = np.all(array1 < 8)
print(result)

False
True


In [143]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# check if all element in each row is greater than 5
result_row = np.all(array1 > 5, axis = 1)
print(result_row)

# check if all element in each column is less than 8
result_column = np.all(array1 < 8, axis = 0)
print(result_column)

[False False  True]
[ True False False]


In [144]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])
print("array1: \n", array1)
print("array2: \n", array2)
print("array3: \n", array3)
result = np.stack((array1,array2,array3))
print("Result: \n",result)

array1: 
 [1 2 3]
array2: 
 [4 5 6]
array3: 
 [7 8 9]
Result: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
np.vstack((array1,array2,array3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.hstack((array1,array2,array3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Stack operation is used to join a sequence of arrays into a new matrix

In [2]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print("array1: \n", array1)
print("array2: \n",array2)

result = np.stack((array1,array2), axis=0)
print("Result: \n",result)

array1: 
 [1 2 3]
array2: 
 [4 5 6]
Result: 
 [[1 2 3]
 [4 5 6]]


In [6]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print("array1: \n",array1)
print("array2: \n",array2)

result = np.stack((array1,array2),axis= 1)
print("Result: \n",result)

array1: 
 [1 2 3]
array2: 
 [4 5 6]
Result: 
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

# calculate the sum along columns (axis 0)
col = np.sum(array1, axis= 0)
print("sum along columns:")
print(col)

# calculate the average along columns (axis 0)
col = np.mean(array1, axis= 0)
print("Average along columns:")
print(col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum along columns:
[12 15 18]
Average along columns:
[4. 5. 6.]


In [11]:
# create a 2D NumPy array
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate the sum along rows (axis 1)
rows = np.sum(array1, axis=1)
print("Sum along rows:")
print(rows)

# calculate the average along rows (axis 1)
rows = np.mean(array1, axis = 1)
print("Average along rows:")
print(rows)

Sum along rows:
[ 6 15 24]
Average along rows:
[2. 5. 8.]


Masked array is like an ordinary NumPy array where some values are masked or ignored

Masked arrays are useful when working with datasets that contain invalid, missing, or unwanted values.

In [12]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# create a condition
m = array1 > 5

In [13]:
m

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [15]:
# apply the filter to the array
ma = array1[m]

print("Original array:")
print(array1)
print("Filtered array:")
print(ma)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Filtered array:
[6 7 8 9]


In [16]:
from numpy.ma import MaskedArray

# create a NumPy array
array1 = np.array([1, 2, 3, 4, 5])

# create a mask based on a condition
mask = array1 > 2

# create a MaskedArray using the original array and the mask
masked_arr = MaskedArray(array1, mask)

print("Original array:")
print(array1)
print("Masked array:")
print(masked_arr)

Original array:
[1 2 3 4 5]
Masked array:
[1 2 -- -- --]


An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.

In [18]:
array1 = np.array([0, 2, 4])
array2 = np.array([[6], [8], [4]])

# add arrays of different dimension
# size of array1 expands to match with array2
result = array1 + array2

print(result)

[[ 6  8 10]
 [ 8 10 12]
 [ 4  6  8]]


In [19]:
## Scaler Broadcasting
# 1-D array
array1 = np.array([1, 2, 3])

# scalar
number = 5

# add scalar and 1-D array
sum = array1 + number
print(sum)

[6 7 8]


In [20]:
array1 = np.array([1,2,3,4,5])
number = 10

#  number sums up with each array element
result = array1 - number
print(result)

[-9 -8 -7 -6 -5]


In [ ]:
# NumPy Universal Functions

# Arithmentic functions like add(), subtract() and multiply()
# Trigonometric functions like sin(), cos() and tan()
# Aggregation functions like mean(), min() and max()
# These functions perform vectorized operations.

In [21]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# addition
result1 = np.add(array1, array2)

# multiplication
result2 = np.multiply(array1, array2)

print("Addition:", result1)
print("Multiplication", result2)

Addition: [ 6  8 10 12]
Multiplication [ 5 12 21 32]


In [25]:
# array of angles in radians
angles = np.array([0, 0.5, 0.6, 0.7, 0.8, 1])
print("Angles:",angles)

# compute the sine of the angles
sine_values = np.sin(angles)
print("Sine values:", sine_values)

# compute the cosine of the angles
cosine = np.cos(angles)
print("Cosine values:", cosine)

print("Tangent values:", np.tan(angles))

Angles: [0.  0.5 0.6 0.7 0.8 1. ]
Sine values: [0.         0.47942554 0.56464247 0.64421769 0.71735609 0.84147098]
Cosine values: [1.         0.87758256 0.82533561 0.76484219 0.69670671 0.54030231]
Tangent values: [0.         0.54630249 0.68413681 0.84228838 1.02963856 1.55740772]


In [26]:
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)
print("Median is:",median)

# find the smallest element
result = np.min(array1)
print("Smallest element is", result)

# find the largest element
result = np.max(array1)
print("Largest element is", result)

Median is: 3.0
Smallest element is 1
Largest element is 5


In [27]:
print(np.max(array1))

5


In [28]:
import time

start = time.time()

list1 = list(range(10000000))

for i in range(len(array1)):
    list1[i] += 10

end = time.time()

print("For loop time:", end - start)

For loop time: 0.5193309783935547


In [29]:
import time

start = time.time()

array1 = np.array(list(range(10000000)))

result = array1 + 10

end = time.time()

print("Vectorization time:", end - start)


Vectorization time: 1.2344441413879395


In [30]:
# Mathematical Expressions
# array
X = np.array([1, 2, 3, 4])

# evaluate 2log(X) + e^3
result = 2 * np.log(X) + np.exp(3)

print(result)

[20.08553692 21.47183128 22.2827615  22.85812565]


In [31]:
# evaluate e^X - 1
sec_result = np.exp(X) - 1
print(sec_result)

[ 1.71828183  6.3890561  19.08553692 53.59815003]


In [32]:
third_result = np.log2(5)
print(third_result)

2.321928094887362


In [33]:
2 ** 2.321928094887362

4.999999999999999

In [34]:
np.log2(15)

np.float64(3.9068905956085187)

In [35]:
2 ** 3.9068905956085187

15.000000000000002