### 1. Import the NumPy library and print its version. 

In [8]:
import numpy as np

### 2. Create a NumPy array containing numbers from 1 to 10. 

In [7]:
numb = np.array(range(1,11))
numb

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 3. Create an array of all zeros with size 10. 

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create an array of all ones with shape (3,3). 

In [16]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 5. Create an identity matrix of size 5×5. 

In [19]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 6. Create an array of even numbers from 2 to 50. 

In [24]:
even = np.array(range(2,51))
even[even % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])