### 1. Import the NumPy library and print its version. 

In [8]:
import numpy as np

### 2. Create a NumPy array containing numbers from 1 to 10. 

In [7]:
numb = np.array(range(1,11))
numb

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 3. Create an array of all zeros with size 10. 

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create an array of all ones with shape (3,3). 

In [16]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 5. Create an identity matrix of size 5×5. 

In [19]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 6. Create an array of even numbers from 2 to 50. 

In [24]:
even = np.array(range(2,51))
even[even % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

### 7. Create an array of odd numbers from 1 to 99. 

In [27]:
odd = np.array(range(1,100))
a = odd[odd % 2 == 1]
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### 8. Generate numbers from 10 to 100 with step size 5. 

In [29]:
b = np.array(range(10,100,5))
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

### 9. Create a NumPy array from a Python list. 

In [43]:
li = list(range(1,30))
print(li)
print(type(li))

a = np.array(li)
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
<class 'numpy.ndarray'>


### 10. Create a NumPy array from a tuple. 

In [52]:
tu = ("a","b",2,5)
print(tu)
print(type(tu))

b = np.array(tu)
print(b)
print(type(b))

('a', 'b', 2, 5)
<class 'tuple'>
['a' 'b' '2' '5']
<class 'numpy.ndarray'>


### 11. Find the shape of an array. 

In [58]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 12. Find the dimensions of an array. 

In [66]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [64]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


### 13. Find the datatype of array elements. 

In [70]:
a = np.array([1,2,3,4])
print(a)
print(a.dtype)

[1 2 3 4]
int64


### 14. Create a random array of size 10. 

In [117]:
b = np.random.rand(10)
print(b)
print(type(b))
print(b.size)

[0.82003764 0.47945468 0.81158228 0.42698433 0.52578521 0.15819021
 0.43615846 0.61075544 0.89238989 0.12943439]
<class 'numpy.ndarray'>
10


### 15. Generate 10 random integers between 1 and 100. 

In [114]:
a = np.random.randint(1,100,size= 10)
a

array([25, 55, 71, 48, 11, 34, 51,  9, 74, 34], dtype=int32)

### 16. Reshape an array of size 12 into (3,4). 

In [126]:
a = np.array([1,2,3,4,5,6,7,8,1,5,9,5])
b = a.reshape(3,4)
print(b)
print(b.shape)


[[1 2 3 4]
 [5 6 7 8]
 [1 5 9 5]]
(3, 4)


### 17. Flatten a 3×3 matrix into a 1D array. 

### 18. Create a 4×4 matrix filled with value 7. 

### 19. Find the size (number of elements) of an array. 