### 1. Import the NumPy library and print its version. 

In [2]:
import numpy as np

In [4]:
print(np.__version__)

2.3.5


### 2. Create a NumPy array containing numbers from 1 to 10. 

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 3. Create an array of all zeros with size 10. 

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create an array of all ones with shape (3,3). 

In [4]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 5. Create an identity matrix of size 5×5. 

In [5]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 6. Create an array of even numbers from 2 to 50. 

In [6]:
even = np.arange(2,51)
even[even % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

### 7. Create an array of odd numbers from 1 to 99. 

In [7]:
odd = np.arange(1,100)
a = odd[odd % 2 == 1]
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### 8. Generate numbers from 10 to 100 with step size 5. 

In [8]:
b = np.arange(10,100,5)
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

### 9. Create a NumPy array from a Python list. 

In [9]:
li = list(range(1,30))
print(li)
print(type(li))

a = np.array(li)
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
<class 'numpy.ndarray'>


### 10. Create a NumPy array from a tuple. 

In [10]:
tu = ("a","b",2,5)
print(tu)
print(type(tu))

b = np.array(tu)
print(b)
print(type(b))

('a', 'b', 2, 5)
<class 'tuple'>
['a' 'b' '2' '5']
<class 'numpy.ndarray'>


### 11. Find the shape of an array. 

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 12. Find the dimensions of an array. 

In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


### 13. Find the datatype of array elements. 

In [14]:
a = np.array([1,2,3,4])
print(a)
print(a.dtype)

[1 2 3 4]
int64


### 14. Create a random array of size 10. 

In [15]:
b = np.random.rand(10)
print(b)
print(type(b))
print(b.size)

[0.48993286 0.90745829 0.30480404 0.00474528 0.87475566 0.55285507
 0.9215598  0.24290394 0.76688243 0.25173408]
<class 'numpy.ndarray'>
10


### 15. Generate 10 random integers between 1 and 100. 

In [16]:
a = np.random.randint(1,100,size= 10)
a

array([66, 77,  7, 91, 98,  2, 92, 76, 69, 87], dtype=int32)

### 16. Reshape an array of size 12 into (3,4). 

In [17]:
a = np.array([1,2,3,4,5,6,7,8,1,5,9,5])
b = a.reshape(3,4)
print(b)
print(b.shape)


[[1 2 3 4]
 [5 6 7 8]
 [1 5 9 5]]
(3, 4)


### 17. Flatten a 3×3 matrix into a 1D array. 

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

fl = arr.flatten()
print(fl)
print(fl.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3 4 5 6 7 8 9]
1


### 18. Create a 4×4 matrix filled with value 7. 

In [19]:
arr = np.full((4,4),7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 19. Find the size (number of elements) of an array. 

In [20]:
arr = np.array([[1,2,3],[2,3,4]])
print(arr)
print(arr.size)

[[1 2 3]
 [2 3 4]]
6


### 20. Create a diagonal matrix with diagonal values [1,2,3,4]. 

In [21]:
matrix = np.diag([1,2,3,4])
matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 21. Convert a float array into an integer array. 

In [22]:
arr = np.array([1.5, 2.8, 3.2, 4.9])
int_arr = arr.astype(int)
print(int_arr)

[1 2 3 4]


### 22. Create an array with values between 0 and 1 using linspace(). 

In [23]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


### 23. Reverse an array. 

In [24]:
arr = np.arange(1,10)
print(arr)

reverse = np.flip(arr)
print(reverse)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


### 24. Sort an array in ascending order. 

In [25]:
arr = np.array([1,5,8,2,4,9,3,6,7])
print(arr)

sort = np.sort(arr)
print(sort)

[1 5 8 2 4 9 3 6 7]
[1 2 3 4 5 6 7 8 9]


### 25. Find the maximum and minimum values in an array. 

In [26]:
arr = np.array([1,5,8,2,4,9,3,6,7])
max = np.max(arr)
print(max)

min = np.min(arr)
print(min)

9
1


### 26. Find the index of maximum value. 

In [27]:
arr = np.array([1,5,8,2,4,9,3,6,7])
ind = np.argmax(arr)
print(ind)

5


### 27. Find the index of minimum value. 

In [28]:
arr = np.array([1,5,8,2,4,9,3,6,7])
ind = np.argmin(arr)
print(ind)

0


### 28. Create a 2×3 matrix and print its transpose. 

In [29]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

tran = np.transpose(matrix)
print(tran)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 29. Concatenate two arrays. 

In [30]:
l1 = np.array([1,2,3,4])
l2 = np.array([2,4,5,6])

add = l1+l2
print(add)

[ 3  6  8 10]


### 30. Split an array into 3 equal parts. 

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

split = np.split(arr,3)

for i in split:
    print(i)

[1 2]
[3 4]
[5 6]


### 31. Add two arrays element-wise. 

In [33]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

result = arr1 + arr2
print(result)

[ 6  8 10 12]


### 32. Subtract two arrays element-wise. 

In [34]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr2 - arr1)

[4 4 4 4]


### 33. Multiply two arrays element-wise. 

In [35]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1*arr2)

[ 5 12 21 32]


### 34. Divide two arrays element-wise. 

In [36]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1/arr2)

[0.2        0.33333333 0.42857143 0.5       ]


### 35. Find square of every element in an array. 

In [37]:
arr = np.array([1,2,3,4])

result = arr **2
print(result)

[ 1  4  9 16]


### 36. Find cube of every element. 

In [38]:
arr = np.array([1,2,3,4])
print(arr**3)

[ 1  8 27 64]


### 37. Calculate square root of array values. 

In [40]:
arr = np.array([1, 4, 9, 16, 25])
result = np.sqrt(arr)
print(result)

[1. 2. 3. 4. 5.]


### 38. Find exponential values of array elements. 

In [41]:
arr = np.array([1, 2, 3, 4])
result = np.exp(arr)
print(result)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


### 39. Find logarithm of array elements. 

In [42]:
arr = np.array([1, 2, 3, 4])
result = np.log(arr)
print(result)

[0.         0.69314718 1.09861229 1.38629436]


### 40. Compute sum of all elements in an array.  

In [43]:
arr = np.array([1, 2, 3, 4])
result = np.sum(arr)
print(result)

10


### 41. Compute mean of array values. 

In [45]:
arr = np.array([1,2,3,4,5])
result = np.mean(arr)
print(result)

3.0


### 42. Compute median of array values. 

In [46]:
arr = np.array([1,2,3,4,5])
result = np.median(arr)
print(result)

3.0


### 43. Compute standard deviation. 

In [47]:
arr = np.array([1,2,3,4,5])
result = np.std(arr)
print(result)

1.4142135623730951


### 44. Compute variance. 

In [48]:
arr = np.array([1,2,3,4,5])
result = np.var(arr)
print(result)

2.0


### 45. Find cumulative sum of elements. 

In [49]:
arr = np.array([1,2,3,4,5])
result = np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


### 46. Find cumulative product of elements. 

In [50]:
arr = np.array([1,2,3,4,5])
result = np.cumprod(arr)
print(result)

[  1   2   6  24 120]


### 47. Find product of all elements in array. 

In [51]:
arr = np.array([1,2,3,4,5])
result = np.prod(arr)
print(result)

120


### 48. Round decimal values to 2 decimal places. 

In [52]:
arr = np.array([1.2345, 2.6789, 3.4567, 4.9876])
result = np.round(arr,2)
print(result)

[1.23 2.68 3.46 4.99]


### 49. Find absolute values of negative numbers. 

In [53]:
arr = np.array([-10, -5, 0, 5, 10])
result = np.abs(arr)
print(result)

[10  5  0  5 10]


### 50. Replace all negative values with zero. 

In [54]:
arr = np.array([-5, 3, -2, 7, -1, 4])
arr[arr < 0] = 0
print(arr)

[0 3 0 7 0 4]


### Section 3: Indexing & Slicing (51-65) 

### 51. Access the first element of an array. 

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


### 52. Access the last element of an array. 

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


### 53. Extract first 5 elements from an array. 

In [9]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[:5])

[10 11 12 13 14]


### 54. Extract last 5 elements from an array. 

In [13]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[:-6:-1])

[20 19 18 17 16]


In [16]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[6:])

[16 17 18 19 20]


### 55. Slice every alternate element. 

In [17]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[::2])

[10 12 14 16 18 20]


### 56. Reverse an array using slicing. 

In [18]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr[::-1])

[20 19 18 17 16 15 14 13 12 11 10]


### 57. Access a specific row in a matrix. 

In [19]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[1])

[4 5 6]


### 58. Access a specific column in a matrix. 

In [21]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[:,0])

[1 4 7]


### 59. Extract a submatrix from a 5×5 matrix. 

In [22]:
matrix = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
submatrix = matrix[1:4, 1:4]
print(submatrix)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


### 60. Replace the third element with value 100. 

In [23]:
arr = np.array([10, 20, 30, 40, 50])
arr[2] = 100
print(arr)

[ 10  20 100  40  50]


### 61. Replace all even numbers with -1. 

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 0] = -1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9]


### 62. Find all elements greater than 50. 

In [25]:
arr = np.array([10, 25, 50, 60, 75, 40, 90])
result = arr[arr > 50]
print(result)

[60 75 90]


### 63. Find indices of elements greater than 50. 

In [26]:
arr = np.array([10, 25, 50, 60, 75, 40, 90])
result = np.where(arr > 50)
print(result)

(array([3, 4, 6]),)


### 64. Select elements divisible by 3. 

In [27]:
arr = np.array([3, 5, 9, 12, 14, 18, 20])
result = arr[arr % 3 == 0]
print(result)

[ 3  9 12 18]


### 65. Extract diagonal elements from a matrix. 

In [28]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

diagonal = np.diag(matrix)
print(diagonal)

[1 5 9]


### Section 4: Matrix Operations (66-80) 

### 66. Add two matrices. 

In [29]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

result = matrix1 + matrix2
print(result)

[[ 6  8]
 [10 12]]


### 67. Subtract two matrices. 

In [30]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

result = matrix2 - matrix1
print(result)

[[4 4]
 [4 4]]


### 68. Multiply two matrices element-wise. 

In [31]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])
result = matrix1 * matrix2
print(result)

[[ 5 12]
 [21 32]]


### 69. Perform matrix multiplication using dot(). 

In [32]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


### 70. Calculate transpose of a matrix. 

In [33]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = np.transpose(matrix)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [35]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
result = matrix.T
print(result)

[[1 4]
 [2 5]
 [3 6]]


### 71. Find determinant of a matrix. 

In [36]:
matrix = np.array([
    [1, 2],
    [3, 4]
])

det = np.linalg.det(matrix)

print(det)

-2.0000000000000004


### 72. Find inverse of a matrix. 

In [37]:
matrix = np.array([
    [1, 2],
    [3, 4]
])
inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


### 73. Find eigenvalues of a matrix. 

In [38]:
matrix = np.array([
    [4, 2],
    [1, 3]
])
result = np.linalg.eigvals(matrix)
print(result)

[5. 2.]


### 74. Find eigenvectors of a matrix. 

In [39]:
matrix = np.array([
    [4, 2],
    [1, 3]
])


eigenvectors = np.linalg.eig(matrix)

print("Eigenvectors:")
print(eigenvectors)

Eigenvectors:
EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


### 75. Compute matrix rank. 

### 76. Create a random 4×4 matrix and find row sums. 

### 77. Find column sums of a matrix. 

### 78. Find row-wise maximum values. 

### 79. Find column-wise minimum values. 

### 80. Create a 5×5 multiplication table matrix. 

## Section 5: Intermediate Level (81-90) 

### 81. Generate a random array and normalize it between 0 and 1. 

### 82. Create a checkerboard pattern matrix (8×8). 

### 83. Find unique elements in an array. 

### 84. Count frequency of each unique value. 

### 85. Shuffle elements of an array randomly. 

### 86. Find common elements between two arrays. 

### 87. Remove duplicate values from an array. 

### 88. Find missing numbers in an array from 1-100. 

### 89. Convert a 1D array into a 3D array. 

### 90. Create a border matrix where borders are 1 and inner values are 0. 

# Section 6: Advanced Level (91-100) 

### 91. Implement one-hot encoding using NumPy only. 

### 92. Standardize an array using z-score normalization. 

### 93. Perform min-max normalization. 

### 94. Create a sliding window from an array. 

### 95. Calculate pairwise Euclidean distance between points. 

### 96. Simulate rolling dice 1000 times and calculate probabilities. 

### 97. Generate a random dataset and calculate covariance matrix. 

### 98. Implement simple linear regression using NumPy only. 

### 99. Create an image as a NumPy matrix and perform grayscale inversion. 

### 100. Build a mini student marks analysis system using NumPy (average, topper, pass/fail, subject-wise         statistics). 